Admin/Models/DonHang.cs
using System;
using System.Collections.Generic;

namespace Admin.Models;

public partial class DonHang
{
    public string IdDonHang { get; set; } = null!;

    public DateTime? NgayTaoDonHang { get; set; }

    public string? DiaChiNhanHang { get; set; }

    public string? DsSanPham { get; set; }

    public int? Chietkhau { get; set; }

    public decimal? ThanhTien { get; set; }

    public string? IdPttt { get; set; }

    public virtual Pttt? IdPtttNavigation { get; set; }

    public virtual ICollection<KhachHang> KhachHangs { get; set; } = new List<KhachHang>();

    public virtual ICollection<PhieuXuat> PhieuXuats { get; set; } = new List<PhieuXuat>();
}

Admin/Controllers/DonHangController.cs
using Admin.ControlData;
using Admin.Models;
using Admin.Models.State;
using Microsoft.AspNetCore.Mvc;
using Nome.Recieve;
namespace Admin.Controllers
{
    public class DonHangController : Controller
    {
        private readonly WebDataContext _webDataContext;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public DonHangController(WebDataContext webDataContext, IWebHostEnvironment hostingEnvironment)
        {
            _webDataContext = webDataContext;
            _hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            List<KhachHang> kh = _webDataContext.KhachHangs.ToList();
            List<DonHang> dh = ReadJson.getList(kh);
            if (dh == null)
            {
                TempData["OrderIsNull"] = "Hiện tại không có đơn hàng";
                return RedirectToAction("Index", "Home");
            }
            return View(dh);
        }

        public IActionResult SeeOrder(string id)
        {
            KhachHang kh = _webDataContext.KhachHangs.FirstOrDefault(kh => kh.IdDonHang == id);

            List<OrderProduct> orderProducts = ReadJson.getListOrder(kh);
            return View(orderProducts);
        }

        public IActionResult AcceptOrder(string id)
        {
            KhachHang kh = _webDataContext.KhachHangs.FirstOrDefault(kh => kh.IdDonHang == id);
            List<OrderProduct> orderProducts = ReadJson.getListOrder(kh);
            DonHang donHang = _webDataContext.DonHangs.FirstOrDefault(dh => dh.IdDonHang == kh.IdDonHang);
            Report.CreateWordReport(kh, donHang, orderProducts);
            StateOrder state = new StateOrder();
            state.IdKH = kh.IdKh;
            state.TrangThai = "Đã duyệt";
            ReadJson.UpdateStateDonHang(state, kh);
            string path = @"../Admin/StoreData/DonHang/" + kh.IdKh + ".json";
            System.IO.File.Delete(path);
            string path2 = @"../Admin/StoreData/SanPhamDaDat/" + kh.IdKh + ".json";
            System.IO.File.Delete(path2);
            return RedirectToAction("Index");
        }

        public IActionResult CancelOrder(string id)
        {
            KhachHang kh = _webDataContext.KhachHangs.FirstOrDefault(kh => kh.IdDonHang == id);
            StateOrder state = new StateOrder();
            state.IdKH = kh.IdKh;
            state.TrangThai = "Đã huỷ";
            ReadJson.UpdateStateDonHang(state, kh);
            string path = @"../Admin/StoreData/DonHang/" + kh.IdKh + ".json";
            System.IO.File.Delete(path);
            string path2 = @"../Admin/StoreData/SanPhamDaDat/" + kh.IdKh + ".json";
            System.IO.File.Delete(path2);
            return RedirectToAction("Index");
        }

        public IActionResult DonDaDuyet()
        {
            string relativePath = @"\wwwroot\reports\"; // Thư mục tương đối từ thư mục gốc nội dung của ứng dụng
            string folderPath = Path.Combine(_hostingEnvironment.ContentRootPath, relativePath);
            if (!Directory.Exists(folderPath))
            {
                return NotFound();
            }

            // Lấy danh sách thư mục và tệp tin
            var directories = Directory.GetDirectories(folderPath);
            var files = Directory.GetFiles(folderPath);

            var model = new FileManagerViewModel
            {
                Directories = directories,
                Files = files
            };

            return View(model);
        }
    }
}

Admin/Views/DonHang/DonDaDuyet.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Admin.Models.State.FileManagerViewModel
<h1>File Manager</h1>

<h2>Directories</h2>
<ul>
    @foreach (var directory in Model.Directories)
    {
        <li>@directory</li>
    }
</ul>

<h2>Files</h2>
<ul>
    @foreach (var file in Model.Files)
    {
        <li>@file</li>
    }
</ul>

Admin/Views/DonHang/Index.cshtml
@model IEnumerable<Admin.Models.DonHang>

@{
    ViewData["Title"] = "Index";
}

<h1>Mục lục</h1>

<p>
    <a asp-action="Create">Tạo mới</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Ngày đặt hàng
            </th>
            <th>
                Địa chỉ nhận hàng
            </th>
            <th>
                Sản phẩm đặt
            </th>
            <th>
                Chiết khấu
            </th>
            <th>
                Tổng đơn hàng
            </th>
            <th>
                Hình thức thanh toán
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayTaoDonHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DiaChiNhanHang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DsSanPham)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Chietkhau)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPttt)
                </td>
                <td>
                    <a asp-action="AcceptOrder" asp-route-id="@item.IdDonHang">Duyệt đơn hàng</a> |
                    <a asp-action="SeeOrder" asp-controller="DonHang" asp-route-id="@item.IdDonHang">Xem Đơn hàng</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdDonHang">Huỷ đơn hàng</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Admin/Views/DonHang/SeeOrder.cshtml
@model IEnumerable<Nome.Recieve.OrderProduct>

@{
    ViewData["Title"] = "Đơn hàng";
}

<h1>Đơn hàng</h1>

<table class="table">
    <thead>
        <tr>
            <th>Tên Sản Phẩm</th>
            <th>Hình Ảnh</th>
            <th>Số Lượng</th>
            <th>Giá</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenSanPham)
            </td>
            <td>
                <img src="~/SanPham/@item.HinhAnhSP" width="280px" height="180px" alt=""/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia)
            </td>
        </tr>
}
    </tbody>
</table>