Admin/Models/KhachHang.cs
using System;
using System.Collections.Generic;

namespace Admin.Models;

public partial class KhachHang
{
    public string IdKh { get; set; } = null!;

    public string? HoTenKh { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public string? DiaChi { get; set; }

    public string? Email { get; set; }

    public string? Std { get; set; }

    public string? GiayPhep { get; set; }

    public decimal? TichDiem { get; set; }

    public string? MatKhau { get; set; }

    public string? LoaiKh { get; set; }

    public string? IdGioHang { get; set; }

    public string? IdDonHang { get; set; }

    public virtual DonHang? IdDonHangNavigation { get; set; }

    public virtual GioHang? IdGioHangNavigation { get; set; }
}

Admin/Controllers/KhachHangsController.cs
using Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Admin.Controllers
{
    public class KhachHangsController : Controller
    {
        private readonly WebDataContext _context;

        public KhachHangsController(WebDataContext context)
        {
            _context = context;
        }

        // GET: KhachHangs
        public async Task<IActionResult> Index()
        {
            var webDataContext = _context.KhachHangs.Include(k => k.IdDonHangNavigation).Include(k => k.IdGioHangNavigation);
            return View(await webDataContext.ToListAsync());
        }
        string codeRandom()
        {
            char[] characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".ToCharArray();
            // Sử dụng Random để chọn ngẫu nhiên các ký tự và số từ mảng
            Random random = new Random();
            // Tạo một chuỗi có độ dài 6 với các ký tự và số ngẫu nhiên
            string maTinhYeu = "";
            for (int i = 0; i < 6; i++)
            {
                // Chọn một phần tử ngẫu nhiên từ mảng characters
                maTinhYeu += characters[random.Next(characters.Length)];
            }
            return maTinhYeu;
        }

        // GET: KhachHangs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .Include(k => k.IdDonHangNavigation)
                .Include(k => k.IdGioHangNavigation)
                .FirstOrDefaultAsync(m => m.IdKh == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public IActionResult Create()
        {
            KhachHang kh = new KhachHang();
            kh.IdKh = codeRandom();
            kh.IdGioHang = kh.IdKh;
            kh.IdDonHang = null;
            return View(kh);
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKh,HoTenKh,NgaySinh,DiaChi,Email,Std,GiayPhep,TichDiem,MatKhau,LoaiKh,IdGioHang,IdDonHang")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                GioHang gh = new GioHang();
                gh.IdGioHang = khachHang.IdKh;
                gh.IdKh = khachHang.IdKh;
                gh.DsSanPham = null;
                _context.GioHangs.Add(gh);
                _context.KhachHangs.Add(khachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDonHang"] = new SelectList(_context.DonHangs, "IdDonHang", "IdDonHang", khachHang.IdDonHang);
            ViewData["IdGioHang"] = new SelectList(_context.GioHangs, "IdGioHang", "IdGioHang", khachHang.IdGioHang);
            return View(khachHang);
        }

        // GET: KhachHangs/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            ViewData["IdDonHang"] = new SelectList(_context.DonHangs, "IdDonHang", "IdDonHang", khachHang.IdDonHang);
            ViewData["IdGioHang"] = new SelectList(_context.GioHangs, "IdGioHang", "IdGioHang", khachHang.IdGioHang);
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("IdKh,HoTenKh,NgaySinh,DiaChi,Email,Std,GiayPhep,TichDiem,MatKhau,LoaiKh,IdGioHang,IdDonHang")] KhachHang khachHang)
        {
            if (id != khachHang.IdKh)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.IdKh))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdDonHang"] = new SelectList(_context.DonHangs, "IdDonHang", "IdDonHang", khachHang.IdDonHang);
            ViewData["IdGioHang"] = new SelectList(_context.GioHangs, "IdGioHang", "IdGioHang", khachHang.IdGioHang);
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .Include(k => k.IdDonHangNavigation)
                .Include(k => k.IdGioHangNavigation)
                .FirstOrDefaultAsync(m => m.IdKh == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang != null)
            {
                _context.KhachHangs.Remove(khachHang);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(string id)
        {
            return _context.KhachHangs.Any(e => e.IdKh == id);
        }
    }
}

Admin/Views/KhachHangs/Create.cshtml
@model Admin.Models.KhachHang

@{
    ViewData["Title"] = "Thêm tài khoản mới";
}

<h1>thêm tài khoản mơi</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdKh" class="control-label">Mã Khách Hàng</label>
                <input asp-for="IdKh" class="form-control" />
                <span asp-validation-for="IdKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoTenKh" class="control-label">Họ và Tên</label>
                <input asp-for="HoTenKh" class="form-control" />
                <span asp-validation-for="HoTenKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label">Ngày Sinh</label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label">Địa Chỉ</label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Std" class="control-label">Số Điện Thoại</label>
                <input asp-for="Std" class="form-control" />
                <span asp-validation-for="Std" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiayPhep" class="control-label">Giấy Phép</label>
                <input asp-for="GiayPhep" class="form-control" />
                <span asp-validation-for="GiayPhep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TichDiem" class="control-label">Điểm Tích Lũy</label>
                <input asp-for="TichDiem" readonly class="form-control" />
                <span asp-validation-for="TichDiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label">Mật Khẩu</label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiKh" class="control-label">Loại Khách Hàng</label>
                <input asp-for="LoaiKh" readonly class="form-control" />
                <span asp-validation-for="LoaiKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdGioHang" class="control-label">Giỏ Hàng</label>
                <input asp-for="IdGioHang" readonly class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="IdDonHang" class="control-label">Đơn Hàng</label>
                <input asp-for="IdDonHang" readonly class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo Mới" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay Lại Danh Sách</a>
</div>

Admin/Views/KhachHangs/Delete.cshtml
@model Admin.Models.KhachHang

@{
    ViewData["Title"] = "Delete";
}

 <h1>Xóa tài khoản khách hàng</h1>

<h3>Bạn có chắc chắn muốn xóa khách hàng này?</h3>
<div>
    <h4>Thông tin khách hàng</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Họ và Tên
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoTenKh)
        </dd>
        <dt class="col-sm-2">
            Ngày Sinh
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class="col-sm-2">
            Địa Chỉ
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            Số Điện Thoại
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Std)
        </dd>
        <dt class="col-sm-2">
            Giấy Phép
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiayPhep)
        </dd>
        <dt class="col-sm-2">
            Điểm Tích Lũy
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TichDiem)
        </dd>
        <dt class="col-sm-2">
            Mật Khẩu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
        <dt class="col-sm-2">
            Loại Khách Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LoaiKh)
        </dd>
        <dt class="col-sm-2">
            Đơn Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdDonHangNavigation.IdDonHang)
        </dd>
        <dt class="col-sm-2">
            Giỏ Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdGioHangNavigation.IdGioHang)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="IdKh" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại danh sách</a>
    </form>
</div>

Admin/Views/KhachHangs/Details.cshtml
@model Admin.Models.KhachHang

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Thông tin khách hàng</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Họ và Tên
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HoTenKh)
        </dd>
        <dt class="col-sm-2">
            Ngày Sinh
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>
        <dt class="col-sm-2">
            Địa Chỉ
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiaChi)
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            Số Điện Thoại
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Std)
        </dd>
        <dt class="col-sm-2">
            Giấy Phép
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiayPhep)
        </dd>
        <dt class="col-sm-2">
            Điểm Tích Lũy
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TichDiem)
        </dd>
        <dt class="col-sm-2">
            Mật Khẩu
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
        <dt class="col-sm-2">
            Loại Khách Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LoaiKh)
        </dd>
        <dt class="col-sm-2">
            Đơn Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdDonHangNavigation.IdDonHang)
        </dd>
        <dt class="col-sm-2">
            Giỏ Hàng
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdGioHangNavigation.IdGioHang)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdKh">Chỉnh sửa</a> |
    <a asp-action="Index">Quay Lại Danh Sách</a>
</div>

Admin/Views/KhachHangs/Edit.cshtml
@model Admin.Models.KhachHang

@{
    ViewData["Title"] = "Edit";
}

<h1>Chỉnh sửa thông tin khách hàng</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdKh" />
            <div class="form-group">
                <label asp-for="HoTenKh" class="control-label">Họ và Tên</label>
                <input asp-for="HoTenKh" class="form-control" />
                <span asp-validation-for="HoTenKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NgaySinh" class="control-label">Ngày Sinh</label>
                <input asp-for="NgaySinh" class="form-control" />
                <span asp-validation-for="NgaySinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiaChi" class="control-label">Địa Chỉ</label>
                <input asp-for="DiaChi" class="form-control" />
                <span asp-validation-for="DiaChi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Std" class="control-label">Số Điện Thoại</label>
                <input asp-for="Std" class="form-control" />
                <span asp-validation-for="Std" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiayPhep" class="control-label">Giấy Phép</label>
                <input asp-for="GiayPhep" class="form-control" />
                <span asp-validation-for="GiayPhep" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TichDiem" class="control-label">Điểm Tích Lũy</label>
                <input asp-for="TichDiem" class="form-control" />
                <span asp-validation-for="TichDiem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatKhau" class="control-label">Mật Khẩu</label>
                <input asp-for="MatKhau" class="form-control" />
                <span asp-validation-for="MatKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LoaiKh" class="control-label">Loại Khách Hàng</label>
                <input asp-for="LoaiKh" class="form-control" />
                <span asp-validation-for="LoaiKh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdGioHang" class="control-label">Giỏ Hàng</label>
                <select asp-for="IdGioHang" class="form-control" asp-items="ViewBag.IdGioHang"></select>
                <span asp-validation-for="IdGioHang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdDonHang" class="control-label">Đơn Hàng</label>
                <select asp-for="IdDonHang" class="form-control" asp-items="ViewBag.IdDonHang"></select>
                <span asp-validation-for="IdDonHang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu Thay Đổi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay Lại Danh Sách</a>
</div>

Admin/Views/KhachHangs/Index.cshtml
@model IEnumerable<Admin.Models.KhachHang>

@{
    ViewData["Title"] = "Index";
}


<div style="width: 500px;">
    <h1>Danh sách khách hàng</h1>

    <p>
        <a asp-action="Create">Thêm khách hàng</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Họ và tên
                </th>
                <th>
                    Ngày sinh
                </th>
                <th>
                    Địa chỉ
                </th>
                <th>
                    Email
                </th>
                <th>
                    Std
                </th>
                <th>
                    Giấy phép
                </th>
                <th>
                    Tích điểm
                </th>
                <th>
                    Mật khẩu
                </th>
                <th>
                    Loại khách hàng
                </th>
                <th>
                    Mã đơn hàng
                </th>
                <th>
                    Mã giỏ hàng
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTenKh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NgaySinh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DiaChi)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Std)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GiayPhep)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TichDiem)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MatKhau)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LoaiKh)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdDonHangNavigation.IdDonHang)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdGioHangNavigation.IdGioHang)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-controller="KhachHangs" asp-route-id="@item.IdKh">Edit</a> |
                        <a asp-action="Details" asp-controller="KhachHangs" asp-route-id="@item.IdKh">Details</a> |
                        <a asp-action="Delete" asp-controller="KhachHangs" asp-route-id="@item.IdKh">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>